name: PR Follows Template

on:
    pull_request_target:
        types: [opened, edited, synchronize, reopened]

permissions:
    pull-requests: write
    issues: write
    contents: read

jobs:
    template-check:
        runs-on: ubuntu-latest
        if: github.actor != 'renovate[bot]'
        steps:
            - name: Checkout base branch
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - name: Enforce Template
              uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const path = require('path');
                      const script = require(path.resolve('.github/scripts/pr-template.js'));
                      await script({ github, context, core });

    auto-apply-tags:
        runs-on: ubuntu-latest
        if: |
            always() &&
            github.actor != 'renovate[bot]' &&
            (needs.template-check.result == 'success' || needs.template-check.result == 'skipped')
        needs: [template-check]
        steps:
            - name: Checkout base branch
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - name: Auto-apply tag
              uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const path = require('path');
                      const script = require(path.resolve('.github/scripts/auto-tags.js'));
                      await script({ github, context, core });
